In [2]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

In [3]:
data = pd.read_csv("data.csv")
data

x        y
0  -4.0000  45.0000
1  -3.5789  37.3546
2  -3.1579  30.4183
3  -2.7368  24.1911
4  -2.3158  18.6731
5  -1.8947  13.8643
6  -1.4737   9.7645
7  -1.0526   6.3740
8  -0.6316   3.6925
9  -0.2105   1.7202
10  0.2105   0.4571
11  0.6316  -0.0970
12  1.0526   0.0582
13  1.4737   0.9224
14  1.8947   2.4958
15  2.3158   4.7784
16  2.7368   7.7701
17  3.1579  11.4709
18  3.5789  15.8809
19  4.0000  21.0000

In [4]:
# Cree un objeto de tipo `PolynomialFeatures` con grado `2`
poly = PolynomialFeatures(2)
poly

PolynomialFeatures()

In [5]:
# Transforme la columna `x` del dataset `data` usando el objeto `poly`
x_poly = poly.fit_transform(data[["x"]]).round(3)
x_poly

array([[ 1.   , -4.   , 16.   ],
       [ 1.   , -3.579, 12.809],
       [ 1.   , -3.158,  9.972],
       [ 1.   , -2.737,  7.49 ],
       [ 1.   , -2.316,  5.363],
       [ 1.   , -1.895,  3.59 ],
       [ 1.   , -1.474,  2.172],
       [ 1.   , -1.053,  1.108],
       [ 1.   , -0.632,  0.399],
       [ 1.   , -0.21 ,  0.044],
       [ 1.   ,  0.21 ,  0.044],
       [ 1.   ,  0.632,  0.399],
       [ 1.   ,  1.053,  1.108],
       [ 1.   ,  1.474,  2.172],
       [ 1.   ,  1.895,  3.59 ],
       [ 1.   ,  2.316,  5.363],
       [ 1.   ,  2.737,  7.49 ],
       [ 1.   ,  3.158,  9.972],
       [ 1.   ,  3.579, 12.809],
       [ 1.   ,  4.   , 16.   ]])

In [6]:
import numpy as np

In [14]:
# Fije la tasa de aprendizaje en 0.0001 y el número de iteraciones en 1000
learning_rate = 0.0001
n_iterations = 500

In [15]:
# Defina el parámetro inicial `params` como un arreglo de tamaño 3 con ceros
params = np.zeros(x_poly.shape[1])
for epoch in range(n_iterations):

    # Compute el pronóstico con los parámetros actuales
    y_pred = np.dot(x_poly, params)

    # Calcule el error
    error = [yt-yp for yt,yp in zip(data.y,y_pred)]
    #error_2 = [ e**2 for e in error]
    #mse = sum(error_2)/len(error)

    # Calcule el gradiente
    gradient = -2*np.sum(np.multiply(x_poly,np.array(error)[:,np.newaxis]),axis =  0)
    
    # Actualice los parámetros
    params = params - learning_rate * gradient

    #print(f"el error en la iteración {epoch} es {error}")

In [16]:
gradient

array([-5.86057825e+00,  4.76512490e-03,  5.58116245e-01])

In [17]:
params

array([ 0.66661408, -2.99983096,  2.03175709])

In [11]:
expected = np.array([0.666, -3.0, 2.032])
np.allclose(params, expected, atol=1e-3)

True

In [12]:
x_expected = np.array(
        [
            [1.0, -4.0, 16.0],
            [1.0, -3.579, 12.809],
            [1.0, -3.158, 9.972],
            [1.0, -2.737, 7.49],
            [1.0, -2.316, 5.363],
            [1.0, -1.895, 3.59],
            [1.0, -1.474, 2.172],
            [1.0, -1.053, 1.108],
            [1.0, -0.632, 0.399],
            [1.0, -0.21, 0.044],
            [1.0, 0.21, 0.044],
            [1.0, 0.632, 0.399],
            [1.0, 1.053, 1.108],
            [1.0, 1.474, 2.172],
            [1.0, 1.895, 3.59],
            [1.0, 2.316, 5.363],
            [1.0, 2.737, 7.49],
            [1.0, 3.158, 9.972],
            [1.0, 3.579, 12.809],
            [1.0, 4.0, 16.0],
        ]
    )

In [13]:
for i in range(x_poly.shape[0]):
        for j in range(x_poly.shape[1]):
            assert x_poly[i, j] == x_expected[i, j]